In [1]:
# Business Problem

# A retail company wants to understand:

# Who spends the most?
# Which products are most popular?
# Which marketing campaigns perform best?
# Which purchase channels customers prefer?
# What factors influence customer spending?

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
sns.set_theme(style = "whitegrid")
plt.style.use("ggplot")

In [3]:
df = pd.read_csv(r"C:\Users\mahen\Downloads\marketing_campaign.csv",sep = "\t")

In [4]:
df.head()

  ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0  5524,1957,Graduation,Single,58138,0,0,04-09-20...
1  2174,1954,Graduation,Single,46344,1,1,08-03-20...
2  4141,1965,Graduation,Together,71613,0,0,21-08-...
3  6182,1984,Graduation,Together,26646,1,0,10-02-...
4  5324,1981,PhD,Married,58293,1,0,19-01-2014,94,...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                    --------------  -----
 0   ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response  2240 non-null   object
dtypes: object(1)
memory usage: 17.6+ KB

In [6]:
df.describe()

       ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count                                                2240
unique                                               2240
top     5524,1957,Graduation,Single,58138,0,0,04-09-20...
freq                                                    1

In [7]:
df.shape

(2240, 1)

In [8]:
df.isnull().sum()

ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response    0
dtype: int64

In [9]:
df.isnull()

      ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
2235                                              False
2236                                              False
2237                                              False
2238                                              False
2239                                              False

[2240 rows x 1 columns]

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response'], dtype='object')

In [13]:
df["Income"] = df["Income"].astype(str)

KeyError: 'Income'

In [15]:
df["Income"].dtypes

KeyError: 'Income'

In [ ]:
df["Income"]=df["Income"].astype(float)

In [ ]:
df.duplicated().sum()

In [ ]:
df["Dt_Customer"].dtype

In [ ]:
df.duplicated().sum()

In [56]:
df["Dt_Customer"].dtype

KeyError: 'Dt_Customer'

In [ ]:
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    format="%d-%m-%Y"
)

In [ ]:
df["Dt_Customer"].head(10)

In [ ]:
df.info()

In [ ]:
current_year = datetime.now().year

In [ ]:
df["Age"] = current_year - df["Year_Birth"]

In [ ]:
df[["Year_Birth", "Age"]].head()

In [ ]:
# I created a Children feature because the total number of children in a household 
# is more useful for analysis than keeping kids and teenagers separate. It simplifies 
#     the data and helps analyze how family size influences customer spending and 
#     purchasing behavior.

In [ ]:
df["Children"] = df["Kidhome"] + df["Teenhome"]

# Total Spending

The company wants to know:-

How much has each customer spent in total?

In [ ]:
df["Total_Spending"]=(
    df["MntWines"]
    + df["MntFruits"]
    + df["MntMeatProducts"]
    + df["MntFishProducts"]
    + df["MntSweetProducts"]
    + df["MntGoldProds"]
)

In [ ]:
df["Total_Spending"].head(10)

# Total Purchases

Why do we need this?

Customers purchase through variety of places:

Website
Catalog
Store

Instead of analyzing three columns separately, create one total.

In [19]:
df["Total_Purchases"] = (
    df["NumWebPurchases"]
    + df["NumCatalogPurchases"]
    + df["NumStorePurchases"]
)

KeyError: 'NumWebPurchases'

# Total Campaigns Accepted
Why?

The company ran multiple marketing campaigns. We want to know how many campaigns each customer accepted.

In [ ]:
df["Campaigns_Accepted"] = (
    df["AcceptedCmp1"]
    + df["AcceptedCmp2"]
    + df["AcceptedCmp3"]
    + df["AcceptedCmp4"]
    + df["AcceptedCmp5"]
)

In [ ]:
df.head()

# EDA Workflow

# EDA 1: Age Distribution
Business Question

What is the age distribution of our customers?

In [ ]:
plt.figure(figsize=(10,6))

sns.histplot(
    data = df,
    x = "Age",
    bins = 20,
    kde = True,
    color = "steelblue"
)

plt.title("Age Distribution of Customers")
plt.xlabel("Age")
plt.ylabel("Number of Customers")

plt.show()

# Business Insights
Most customers are between 45 and 65 years old.
The highest number of customers are around 50–55 years old.
There are very few customers below 35 years of age.
The number of customers decreases after 70 years.
A few customers have ages above 120 years, which may be incorrect and should be checked.

# EDA 2: Income Distribution
🎯 Business Question

What is the income distribution of customers?

In [ ]:
plt.figure(figsize=(10, 6))

sns.histplot(
    data = df,
    x = "Income",
    bins = 30,
    kde = True,
    color = "green"
)

plt.title("Income Distribution of Customers")
plt.xlabel("Income")
plt.ylabel("Number of Customers")

plt.show()

# EDA 3: Education Distribution
🎯 Business Question

Which education level has the highest number of customers?

In [ ]:
plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    x="Education",
    hue="Marital_Status",
    palette="viridis"
)

plt.title("Customer Distribution by Education")
plt.xlabel("Education")
plt.ylabel("Number of Customers")

plt.xticks(rotation=45)
plt.legend(title="Marital Status")

plt.show()

# EDA 4: Marital Status Distribution
🎯 Business Question

What is the marital status of our customers?

In [ ]:
plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    x= "Marital_Status",
    hue = "Marital_Status",
    legend = False,
    palette = "Set2"
)

plt.title("Customer Distribution by Marital Status")
plt.xlabel("Marital Status")
plt.ylabel("Number of Customers")

plt.xticks(rotation = 45)
plt.show()

# Business Insights

After looking at the graph, write insights such as:

The majority of customers are Married
The least common marital status is Alone
The company has a diverse customer base with different marital statuses.

# EDA 5: Product Spending Analysis
Business Question

Which product categories do customers spend the most money on?

# We have six product columns:

1-MntWines
2-MntFruits
3-MntMeatProducts
4-MntFishProducts
5-MntSweetProducts
6-MntGoldProds

# Calculating total spending for each product

In [ ]:
product_spending = df[[ "MntWines",
        "MntFruits",
        "MntMeatProducts",
        "MntFishProducts",
        "MntSweetProducts",
        "MntGoldProds"]].sum()

product_spending

In [ ]:
product_spending.index=[
    "Wine",
    "Fruits",
    "Meat",
    "Fish",
    "Sweets",
    "Gold"
]

In [ ]:
product_spending = df[
    [
        "MntWines",
        "MntFruits",
        "MntMeatProducts",
        "MntFishProducts",
        "MntSweetProducts",
        "MntGoldProds"
    ]
].sum()


    
product_share=(product_spending/product_spending.sum()*100).sort_values(ascending=False)
product_share

In [ ]:
product_spending

In [ ]:
plt.figure(figsize=(10,6))

product_spending.sort_values(ascending = False).plot(
     kind="bar"
 )

plt.title("Total Spending by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Total Spending")

plt.xticks(rotation = 45)
plt.show()

# Business Insights
Wine has the highest customer spending among all product categories.
Meat products are the second-highest spending category.
Fruits, fish, and sweets have relatively lower spending.
Gold products also contribute a good amount of customer spending.
The company should focus more on Wine and Meat products while finding ways to increase sales of lower-performing categories.

# EDA 6: Which channel do customers use the most?
 Business Question

Do customers prefer buying through the website, catalog, or physical store?

In [ ]:
purchase_channels= df[[
    "NumWebPurchases",
        "NumCatalogPurchases",
        "NumStorePurchases"
]].sum()

purchase_channels

In [ ]:
purchase_channels.index= [
    "Web",
    "Catalog",
    "Store"
]

In [ ]:
plt.figure(figsize=(8,5))

purchase_channels.sort_values(ascending=False).plot(
    kind="bar"
)

plt.title("Total Purchases by Channel")
plt.xlabel("Purchase Channel")
plt.ylabel("Number of Purchases")

plt.xticks(rotation=0)

plt.show()

# Business Insights
Store purchases are the highest, showing that customers prefer buying from physical stores.
Web purchases are the second most-used channel.
Catalog purchases are the lowest among the three channels.
The company can focus on improving its online and catalog experience to increase purchases through these channels.
Since stores are the strongest channel, the company should continue supporting its physical-store customers.

# EDA 7 — Campaign Performance
Business Question

Which marketing campaign was most successful in getting customers to accept the offer?

In [ ]:
campaign_response = df[
    [
        "AcceptedCmp1",
        "AcceptedCmp2",
        "AcceptedCmp3",
        "AcceptedCmp4",
        "AcceptedCmp5",
        "Response"  
    ]
].sum()

In [ ]:
campaign_response.index=[
    "Campaign 1",
    "Campaign 2",
    "Campaign 3",
    "Campaign 4",
    "Campaign 5",
    "Latest Campaign"
]

In [ ]:
plt.figure(figsize=(12,6))

campaign_response.sort_values(ascending=False).plot(
    kind="bar"
)

plt.title("Marketing Campaign Performance")
plt.xlabel("Campaign")
plt.ylabel("Number of Customers")

plt.xticks(rotation=45)

plt.show()

# EDA 8 — Does Income Affect Spending?
🎯 Business Question

Do customers with higher income tend to spend more?

In [ ]:
plt.figure(figsize=(10,6))

sns.scatterplot(
    data= df,
    x= "Income",
    y ="Total_Spending"
)
plt.title("Income vs Total Spending")
plt.xlabel("Income")
plt.ylabel("Total Spending")

plt.show()

# Business Insights – Income vs Total Spending
1-Most customers have an income between 20,000 and 80,000 and their spending is generally lower than high-income customers.

2-Customers with income above 80,000 show higher spending potential.

3-A few customers have income above 100,000, making them potential high-value customers.

4-The company can target high-income customers with premium products and personalized offers.

5-For customers in the 20,000–80,000 range, the company can use discounts and bundle offers to increase spending.

6-This can help the company increase revenue by using different offers for different income groups.

# EDA 9 — Does Age Affect Spending?
Business Question

Do older customers spend more than younger customers?

This helps the business understand whether age should be considered when creating marketing offers.

In [ ]:
plt.figure(figsize=(10,6))

sns.scatterplot(
    data = df,
    x="Age",
    y = "Total_Spending"
)

plt.title("Age vs Total Spending")
plt.xlabel("Age")
plt.ylabel("Total Spending")

plt.show()

# Business Insights – Age vs Total Spending
Customers aged around 40–60 years show stronger spending levels.
Customers below 30 years generally have lower spending.
Spending varies across age groups, so age alone does not fully explain customer spending.
The company can target the 40–60 age group with premium products and personalized offers.
For younger customers, discounts and attractive bundles could help increase spending.
The company should also remove unrealistic age values before making final business decisions.

# EDA 10 — Income Outliers
Business Question

Are there unusual income values that can affect our analysis?

In [ ]:
plt.figure(figsize=(10, 5))

sns.boxplot(data=df, x="Income")

plt.title("Income Distribution and Outliers")
plt.xlabel("Income")

plt.show()

# Business Insights – Income Outliers
Most customers have income within the normal range, while a few customers have unusually high income.
These high-income values can increase the average income and affect the analysis.
The company should check these records before using average income for business decisions.
For customer targeting, these high-income customers can be considered potential high-value customers and offered premium products or personalized offers.

# EDA 11 — Correlation Heatmap
Business Question

Which factors are related to customer spending and purchasing behavior?

In [ ]:
plt.figure(figsize=(14, 10))

corr = df.select_dtypes(include="number").corr()

sns.heatmap(
    corr,
    cmap="coolwarm",
    annot=False
)

plt.title("Correlation Heatmap")
plt.show()

# EDA 12 — Top 10 High-Value Customers

In [ ]:
top_customers = df[
    ["ID","Income","Age","Total_Spending","Total_Purchases"]
].sort_values(
    "Total_Spending",
    ascending = False
).head(10)

top_customers

In [ ]:
top_customers = df[
    ["ID","Total_Spending","Total_Purchases"]].sort_values("Total_Spending",ascending= False).head(10)
top_customers

# EDA 13 — Customer Spending by Education

We're going to do one final useful EDA before moving to the final business insights.

Business Question

Does customer education level affect total spending?

In [ ]:
plt.figure(figsize=(10, 6))

sns.barplot(
    data=df,
    x="Education",
    y="Total_Spending"
)

plt.title("Average Spending by Education")
plt.xlabel("Education")
plt.ylabel("Average Total Spending")

plt.xticks(rotation=45)

plt.show()

# Business Insights – Average Spending by Education
Graduation customers have the highest average spending.

PhD and Master customers also show relatively high spending.

Basic education customers have the lowest average spending.

The company can focus premium products and personalized offers on higher-spending education groups.

For lower-spending groups, discounts and bundle offers can help increase purchases.

## Final Business Insights & Recommendations

In [14]:
df["Total_Spending"].describe()

KeyError: 'Total_Spending'

In [15]:
df["Customer_Segment"] = pd.cut(
    df["Total_Spending"],
    bins=[-1, 68.75, 396, 1045.50, float("inf")],
    labels=["Low Value", "Medium Value", "High Value", "VIP"]
)

KeyError: 'Total_Spending'

In [16]:
df["Customer_Segment"].value_counts()

KeyError: 'Customer_Segment'

In [17]:
df["Customer_Segment"].value_counts(normalize=True) * 100

KeyError: 'Customer_Segment'

# Profile the segments

In [18]:
segment_analysis = df.groupby(
    "Customer_Segment",
    observed=True
)[
    ["Income", "Total_Spending", "Total_Purchases"]
].mean()

segment_analysis

KeyError: 'Customer_Segment'